
modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/YeoXuHang/Geode-Plus/issues"
[[mods]]
modId = "geode"
version = "${version}"
displayName = "Geode+"
displayURL="https://www.curseforge.com/minecraft/mc-mods/geode-forge-fabric"
logoFile = "icon.png"
authors = "yeoxuhang, mineblock11, SquizzleDizzle"
description = '''
A Forge/Fabric mod that add geodes to Minecraft Overworld, Nether and even The End!
'''
[[dependencies.geode]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.geode]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"
