modLoader = "javafml"
loaderVersion = "[46,)"
license = "Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported"
issueTrackerURL = "https://github.com/YeoXuHang/Geode-Plus/issues"
[[mods]]
modId = "geode_plus"
version = "${version}"
displayName = "Geode+"
displayURL="https://www.curseforge.com/minecraft/mc-mods/geode-plus"
logoFile = "icon.png"
authors = "yeoxuhang, SquizzleDizzle"
description = '''
A Forge/Fabric mod that add geodes to Minecraft Overworld, Nether and even The End!
'''
[[dependencies.geode_plus]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.geode_plus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
